# This workflow releases the current package to a dedicated private CodeArtifact repository.
# One repository may publish more than one package. For more details refer to the release-package Action.
name: Release

on:
  repository_dispatch:
    types: [run-release]
  push:
    branches:
      - main
      - "dev-v3-*"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    uses: cloudscape-design/actions/.github/workflows/release.yml@release-build-tree
    secrets: inherit
    with:
      publish-packages: lib/components,lib/components-themeable
      project-name: Beta-Importer-v2
      role-to-assume: arn:aws:iam::084828579018:role/Beta-Shared-GitHubActionRole5D264369-mwZWAVVl9B2R
