name: Visual Regressions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:

env:
  VISUAL_REGRESSION_SNAPSHOT_DIRECTORY: "__image_snapshots__"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: "Get reference run id"
        run: |
          echo "RUN_ID=`gh run --repo $GITHUB_REPOSITORY --branch main list --workflow "Visual Regressions" --json databaseId --jq .[0].databaseId`" >> $GITHUB_ENV
          echo "Reference snapshots created in run ${RUN_ID}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: visual-regression-snapshots
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ env.RUN_ID }}
          path: ${{ env.VISUAL_REGRESSION_SNAPSHOT_DIRECTORY }}
      - run: npm install
      - run: npm run build
      - run: npm run test:visual
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-regression-snapshots-results
          path: ${{ env.VISUAL_REGRESSION_SNAPSHOT_DIRECTORY }}
  update:
    name: Update Snapshots
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run test:visual:update
      - uses: actions/upload-artifact@v4
        with:
          name: visual-regression-snapshots
          path: ${{ env.VISUAL_REGRESSION_SNAPSHOT_DIRECTORY }}
